Repository cherrypick-project/cherry-front, pull requests merged in 2022-03, with the labels that each got.

#6 feature : 버튼 아토믹 디자인 적용 및 스토리 작성
  .storybook/preview.js
  src/App.jsx
  src/components/UI/atoms/buttons/Buttons.stories.js
  src/components/UI/atoms/buttons/CategorySelectButton.jsx
  src/components/UI/atoms/buttons/CherryPickStartButton.jsx
  src/components/UI/atoms/buttons/DeleteAllButton.jsx
  src/components/UI/atoms/buttons/MoreLectureButton.jsx
  src/components/UI/atoms/buttons/RetryButton.jsx
  src/components/UI/atoms/buttons/ReviewButton.jsx
  src/components/UI/atoms/buttons/SatisficationButton.jsx
  src/components/UI/atoms/buttons/SaveButton.jsx
  src/style/GlobalStyle.js
  src/style/responsive.js
  webpack.config.js
Labels: enhancement

#9 feature : atomic design 설계 및 구현
  src/assets/img/arrow_bottom.svg
  src/assets/img/arrow_left.svg
  src/assets/img/arrow_right.svg
  src/assets/img/bookmark.svg
  src/assets/img/bookmark_active.svg
  src/assets/img/close_dark.svg
  src/assets/img/close_w.svg
  src/assets/img/linkIcon.png
  src/components/UI/atoms/buttons/BookMarkButton.jsx
  src/components/UI/atoms/buttons/Buttons.stories.js
  src/components/UI/atoms/buttons/CarouselSlideButton.jsx
  src/components/UI/atoms/buttons/CategoryCancelButton.jsx
  src/components/UI/atoms/buttons/CloseButton.jsx
  src/components/UI/atoms/buttons/MoreLectureButton.jsx
  src/components/UI/atoms/buttons/OriginalLinkButton.jsx
  yarn.lock
Labels: enhancement

#11 refactor : stories 중 props 필요한 것은 args 형식으로 변경
  src/components/UI/atoms/buttons/BookMarkButton.stories.js
  src/components/UI/atoms/buttons/Buttons.stories.js
  src/components/UI/atoms/buttons/CategorySelectButton.jsx
  src/components/UI/atoms/buttons/CategorySelectButton.stories.jsx
  src/components/UI/atoms/buttons/CloseButton.jsx
  src/components/UI/atoms/buttons/CloseButton.stories.js
  src/components/UI/atoms/buttons/DeleteAllButton.jsx
  src/components/UI/atoms/buttons/MoreLectureButton.jsx
  src/components/UI/atoms/buttons/ReviewButton.jsx
  src/components/UI/atoms/buttons/ReviewButton.stories.jsx
Labels: refactoring

#14 feature : 아토믹 디자인 badge UI & 스토리 작성
  src/components/UI/atoms/badges/AgencyBadge.jsx
  src/components/UI/atoms/badges/AgencyBadge.stories.jsx
  src/components/UI/atoms/badges/AgencyResponsiveBadge.jsx
  src/components/UI/atoms/badges/ApproveBadge.jsx
  src/components/UI/atoms/badges/ApproveBadge.stories.js
  src/components/UI/atoms/badges/Badges.stories.js
  src/components/UI/atoms/badges/JobBadge.jsx
  src/components/UI/atoms/badges/JobBadge.stories.js
  src/components/UI/atoms/badges/NumberBadge.jsx
  src/components/UI/atoms/badges/OnlineBadge.jsx
  src/components/UI/atoms/badges/OnlineBadge.stories.js
  src/components/UI/atoms/badges/RecommendBadge.jsx
  src/components/UI/atoms/badges/RecommendBadge.stories.js
  src/components/UI/atoms/badges/SatisfactionBadge.jsx
  src/components/UI/atoms/badges/TeacherBadge.jsx
  src/components/UI/atoms/badges/UserEmailBadge.jsx
  src/components/UI/atoms/badges/UserEmailBadge.stories.js
  src/components/UI/atoms/badges/UserLoginStateBadge.jsx
  src/components/UI/atoms/buttons/BookMarkButton.stories.js
  src/components/UI/atoms/buttons/Buttons.stories.js
  src/components/UI/atoms/buttons/CategorySelectButton.stories.jsx
  src/components/UI/atoms/buttons/CloseButton.stories.js
  src/components/UI/atoms/buttons/ReviewButton.stories.jsx
  src/components/UI/atoms/buttons/SatisfactionButton.jsx
Labels: good first issue

#23 아토믹 디자인 헤더
  src/assets/img/bell.svg
  src/assets/img/bell_active.svg
  src/assets/img/search_m.svg
  src/components/UI/atoms/input/ReviewOneLineInput.stories.js
  src/components/UI/atoms/input/SearchInput.jsx
  src/components/UI/atoms/input/SearchInput.stories.js
  src/components/molecules/header/Header.jsx
  src/components/molecules/header/Header.stories.js
  src/style/responsive.js
Labels: feature
