Repository cherrypick-project/cherry-front, pull requests merged in 2022-04, with the labels that each got.

#30 fix : CaseSensitivePathsPlugin 관련 버그 수정완료
  webpack.config.js
Labels: bug

#33 config : storybook viewport addon 수정
  .storybook/preview.js
Labels: config

#41 feat : 상세페이지 데스크탑 버전 UI 구현
  src/App.jsx
  src/assets/img/smile_grey.svg
  src/assets/img/smile_red.svg
  src/assets/img/star1_red.svg
  src/assets/img/svg_progressBar.svg
  src/assets/img/thumbnail.svg
  src/components/UI/atoms/badges/LargeAgencyBadge.jsx
  src/components/UI/atoms/badges/OfflineBadge.jsx
  src/components/UI/atoms/badges/SmallAgencyBadge.jsx
  src/components/UI/atoms/badges/UserLoginStateBadge.jsx
  src/components/UI/atoms/buttons/BookMarkButton.jsx
  src/components/UI/atoms/buttons/OriginalLinkButton.jsx
  src/components/UI/atoms/buttons/ReviewButton.jsx
  src/components/molecules/detail/AverageScore.jsx
  src/components/molecules/detail/BackgroundOpacity.jsx
  src/components/molecules/detail/LectureDetailTitle.jsx
  src/components/molecules/detail/LectureInfo.jsx
  src/components/molecules/detail/ProgressBar.jsx
  src/components/molecules/detail/ReviewList.jsx
  src/components/molecules/detail/SideBar.jsx
  src/components/molecules/detail/SvgProgressBar.jsx
  src/components/pages/DetailPage.jsx
  src/components/templates/DetailTemplate.jsx
  src/hooks/useCalulateViewport.js
  src/style/responsive.js
  webpack.config.js
Labels: feature

#43 메인 페이지 현재 배울 수 있는 기술
  src/assets/img/Angular.png
  src/assets/img/C.png
  src/assets/img/Django.png
  src/assets/img/Docker.png
  src/assets/img/Java.png
  src/assets/img/JavaScript.png
  src/assets/img/Laravel.png
  src/assets/img/Mysql.png
  src/assets/img/Oracle.png
  src/assets/img/Python.png
  src/assets/img/React.png
  src/assets/img/Redux.png
  src/assets/img/Ruby.png
  src/assets/img/SCSS.png
  src/assets/img/Spring.png
  src/assets/img/TypeScript.png
  src/assets/img/Vue.png
  src/assets/img/Vuex.png
  src/assets/img/emoji_star.png
  src/assets/img/styled component.png
  src/assets/img/webpack.png
  src/components/molecules/availableSkill/AvailableSkill.jsx
  src/components/molecules/header/Header.jsx
  src/components/templates/MainPageTemplate.jsx
  src/style/GlobalStyle.js
Labels: feature

#44 리뷰작성 페이지 UI 구현 완료
  src/App.jsx
  src/assets/img/sad.svg
  src/assets/img/sad_active.svg
  src/assets/img/smile.svg
  src/assets/img/star0.5_red.svg
  src/assets/img/star0_red.svg
  src/components/UI/atoms/buttons/SatisfactionButton.jsx
  src/components/UI/atoms/buttons/SaveButton.jsx
  src/components/UI/atoms/input/ReviewOneLineInput.jsx
  src/components/UI/atoms/input/ReviewProsConsTextarea.jsx
  src/components/pages/ReviewWritePage.jsx
  src/components/templates/ReviewWriteTemplate.jsx
Labels: feature

#46 리뷰 작성하기 페이지 상세 기능 추가 및 스토리 작성
  src/components/UI/atoms/badges/NumberBadge.jsx
  src/components/UI/atoms/buttons/SaveButton.jsx
  src/components/UI/atoms/input/ReviewOneLineInput.jsx
  src/components/molecules/footer/Footer.jsx
  src/components/templates/ReviewWriteTemplate.jsx
  src/components/templates/stories/ReviewWriteTemplate.stories.jsx
Labels: feature

#48 에러페이지, 로딩페이지 UI 스타일링 완료
  src/assets/img/loading.png
  src/components/UI/atoms/buttons/stories/Buttons.stories.js
  src/components/pages/ErrorPage.jsx
  src/components/pages/LoadingPage.jsx
  src/components/templates/ErrorTemplate.jsx
  src/components/templates/LoadingTemplate.jsx
  src/components/templates/stories/ErrorTemplate.stories.jsx
  src/components/templates/stories/LoadingTemplate.stories.jsx
Labels: feature

#52 2번 경력 선택 부분 스크롤 기능 추가
  src/components/templates/SignupTemplate.jsx
Labels: feature

#53 slide 기본정보 선택 파트 드래그 기능 완료
  src/components/templates/SignupTemplate.jsx
Labels: feature

#56 nested routing issue 해결
  src/App.jsx
  src/components/pages/admin/LectureRegisterPage.jsx
  webpack.config.js
Labels: bug

#57 메인페이지 HOT6 캐러셀 PC, 태블릿, 모바일 구현
  src/assets/img/categoryDown.svg
  src/assets/img/emoji_fire.png
  src/assets/img/lectureImg.png
  src/assets/img/rank01.svg
  src/assets/img/rank02.svg
  src/assets/img/rank03.svg
  src/assets/img/rank04.svg
  src/assets/img/rank05.svg
  src/assets/img/rank06.svg
  src/components/UI/atoms/badges/OfflineBadge.jsx
  src/components/UI/atoms/badges/RegularAgencyBadge.jsx
  src/components/UI/atoms/lectureCard/LectureCard.jsx
  src/components/UI/atoms/lectureCard/LectureCardStory.stories.js
  src/components/molecules/availableSkill/AvailableSkill.jsx
  src/components/molecules/hotsix/Hotsix.jsx
  src/components/molecules/hotsix/Hotsix.stories.js
  src/components/templates/MainPageTemplate.jsx
Labels: feature

#58 admin 강의 추가 페이지 UI
  src/components/molecules/admin/lecture-registration/OtherDatas.jsx
  src/components/molecules/admin/lecture-registration/SelectCategory.jsx
  src/components/molecules/admin/lecture-registration/UploadImage.jsx
  src/components/pages/admin/LectureRegisterPage.jsx
  src/components/templates/admin/LectureRegisterTemplate.jsx
Labels: feature

#60 메인페이지 중간 정보 리뷰 UI 완료
  src/components/molecules/signin/SigninStep.jsx
  src/components/molecules/suggestReview/SuggestReview.jsx
  src/components/molecules/suggestReview/SuggestReview.stories.js
  src/components/templates/MainPageTemplate.jsx
  src/components/templates/SignupTemplate.jsx
Labels: feature

#61 강의 추가하기 페이지 스토리 추가
  src/components/molecules/admin/lecture-registration/OtherDatas.jsx
  src/components/molecules/admin/lecture-registration/SelectCategory.jsx
  src/components/molecules/admin/lecture-registration/stories/OtherDatas.stories.jsx
  src/components/molecules/admin/lecture-registration/stories/SelectCategory.stories.jsx
  src/components/molecules/admin/lecture-registration/stories/UploadImage.stories.jsx
  src/components/templates/admin/LectureRegisterTemplate.jsx
  src/components/templates/admin/stories/LectureRegisterTemplate.stories.jsx
Labels: feature

#62 refactor : font-size rem 단위로 모두 수정 및 css 구분 엔터 추가
  src/components/UI/atoms/badges/ApproveBadge.jsx
  src/components/UI/atoms/badges/JobBadge.jsx
  src/components/UI/atoms/badges/LargeAgencyBadge.jsx
  src/components/UI/atoms/badges/NumberBadge.jsx
  src/components/UI/atoms/badges/OfflineBadge.jsx
  src/components/UI/atoms/badges/RecommendBadge.jsx
  src/components/UI/atoms/badges/RegularAgencyBadge.jsx
  src/components/UI/atoms/badges/SatisfactionBadge.jsx
  src/components/UI/atoms/badges/SmallAgencyBadge.jsx
  src/components/UI/atoms/badges/TeacherBadge.jsx
  src/components/UI/atoms/badges/UserEmailBadge.jsx
  src/components/UI/atoms/badges/UserLoginStateBadge.jsx
  src/components/UI/atoms/buttons/CategoryCancelButton.jsx
  src/components/UI/atoms/buttons/CategorySelectButton.jsx
  src/components/UI/atoms/buttons/CherryPickStartButton.jsx
  src/components/UI/atoms/buttons/DeleteAllButton.jsx
  src/components/UI/atoms/buttons/MoreLectureButton.jsx
  src/components/UI/atoms/buttons/OriginalLinkButton.jsx
  src/components/UI/atoms/buttons/RetryButton.jsx
  src/components/UI/atoms/buttons/ReviewButton.jsx
  src/components/UI/atoms/buttons/SatisfactionButton.jsx
  src/components/UI/atoms/buttons/SaveButton.jsx
  src/components/UI/atoms/buttons/SortButton.jsx
  src/components/UI/atoms/buttons/stories/Buttons.stories.js
  src/components/molecules/signin/SigninStep.jsx
  src/components/templates/SignupTemplate.jsx
Labels: refactoring

#65 어드민 헤더 컴포넌트 추가 및 스토리북 데이터 수정
  src/components/molecules/admin/header/AdminHeader.jsx
  src/components/molecules/admin/header/AdminHeader.stories.jsx
  src/components/molecules/admin/lecture-registration/stories/SelectCategory.stories.jsx
  src/components/templates/ReviewWriteTemplate.jsx
  src/components/templates/admin/LectureRegisterTemplate.jsx
Labels: feature, refactoring

#66 fix : Join 폴더명 join 으로 변경
  src/components/UI/atoms/join/DetailInfoButton.jsx
  src/components/UI/atoms/join/DetailInfoButton.stories.js
  src/components/UI/atoms/join/JoinProgress.jsx
  src/components/UI/atoms/join/JoinProgress.stories.js
  src/components/UI/atoms/join/JoinSubmitButton.jsx
  src/components/UI/atoms/join/JoinSubmitButton.stories.js
  src/components/molecules/signin/SigninStep.jsx
  src/components/templates/SignupTemplate.jsx
Labels: bug

#69 카테고리 추가페이지 스타일링 완료
  src/App.jsx
  src/components/UI/atoms/buttons/RetryButton.jsx
  src/components/UI/atoms/buttons/stories/Buttons.stories.js
  src/components/molecules/admin/header/AdminHeader.jsx
  src/components/pages/admin/CategoryRegisterPage.jsx
  src/components/templates/ErrorTemplate.jsx
  src/components/templates/admin/CategoryRegisterTemplate.jsx
  src/components/templates/admin/stories/CategoryRegisterTemplate.stories.jsx
  src/components/templates/admin/stories/LectureRegisterTemplate.stories.jsx
  src/hooks/useCalulateViewport.js
Labels: feature

#71 강의리스트 페이지 UI 구현 완료
  src/App.jsx
  src/components/UI/atoms/buttons/CherryPickStartButton.jsx
  src/components/UI/atoms/buttons/ToggleButton.jsx
  src/components/UI/atoms/buttons/stories/Buttons.stories.js
  src/components/UI/atoms/buttons/stories/ToggleButton.stories.jsx
  src/components/molecules/admin/header/AdminHeader.jsx
  src/components/molecules/admin/lecture-list/LectureListItem.jsx
  src/components/pages/admin/LectureListPage.jsx
  src/components/templates/admin/LectureListTemplate.jsx
  src/components/templates/admin/stories/LectureListTemplate.stories.jsx
Labels: feature

#73 유저리스트 페이지 ui 구현 완료
  src/App.jsx
  src/components/molecules/admin/header/AdminHeader.jsx
  src/components/pages/admin/UserListPage.jsx
  src/components/templates/admin/UserListTemplate.jsx
  src/components/templates/admin/stories/UserListTemplate.stories.jsx
Labels: feature

#74 상세페이지 스토리 추가 및 디자인 수정
  src/components/UI/atoms/buttons/BookMarkButton.jsx
  src/components/molecules/detail/AverageScore.jsx
  src/components/molecules/detail/BackgroundOpacity.jsx
  src/components/molecules/detail/LectureDetailTitle.jsx
  src/components/molecules/detail/LectureInfo.jsx
  src/components/molecules/detail/ReviewList.jsx
  src/components/molecules/detail/SideBar.jsx
  src/components/molecules/detail/stories/SideBar.stories.jsx
  src/components/molecules/header/Header.jsx
  src/components/templates/DetailTemplate.jsx
  src/components/templates/stories/DetailTemplate.stories.jsx
Labels: refactoring

#75 footer 반응형 추가 및 코드 리팩토링
  src/components/molecules/footer/Footer.jsx
Labels: refactoring

#76 detail 페이지 상단 태블릿, 모바일 반응형 수정
  src/components/UI/atoms/badges/LargeAgencyBadge.jsx
  src/components/UI/atoms/buttons/BookMarkButton.jsx
  src/components/UI/atoms/buttons/OriginalLinkButton.jsx
  src/components/UI/atoms/buttons/ReviewButton.jsx
  src/components/molecules/detail/LectureDetailTitle.jsx
  src/components/templates/DetailTemplate.jsx
Labels: refactoring
