Repository cherrypick-project/cherry-front, pull requests merged in 2022-05, with the labels that each got.

#77 상세페이지 반응형 UI 상세수정
  src/components/UI/atoms/badges/RecommendBadge.jsx
  src/components/UI/atoms/badges/SmallAgencyBadge.jsx
  src/components/molecules/detail/AverageScore.jsx
  src/components/molecules/detail/BackgroundOpacity.jsx
  src/components/molecules/detail/LectureDetailTitle.jsx
  src/components/molecules/detail/ReviewList.jsx
  src/components/molecules/detail/SideBar.jsx
  src/components/templates/DetailTemplate.jsx
Labels: refactoring

#79 메인 페이지 3차 카테고리 선택 UI 완성
  src/assets/fonts/SpoqaHanSansNeo-Bold.woff
  src/assets/img/emoji_hmm.png
  src/assets/img/mobileLectureImg.png
  src/components/UI/atoms/lectureCard/LectureCard.jsx
  src/components/UI/atoms/mobileLectureCard/MobileLectureCard.jsx
  src/components/UI/atoms/mobileLectureCard/MobileLectureCard.stories.js
  src/components/molecules/hotsix/Hotsix.jsx
  src/components/molecules/selectCategory/SelectCategory.jsx
  src/components/molecules/selectCategory/SelectCategory.stories.js
  src/components/templates/mainPageTemplate/MainPageTemplate.jsx
  src/components/templates/mainPageTemplate/MainPageTemplate.stories.js
  src/style/GlobalStyle.js
Labels: feature, refactoring, config

#82 검색 결과 페이지 UI
  src/components/UI/atoms/feedback/Feedback.jsx
  src/components/UI/atoms/feedback/Feedback.stories.js
  src/components/UI/atoms/lectureCard/FourLectureCard.jsx
  src/components/UI/atoms/lectureCard/FourLectureCard.stories.js
  src/components/UI/atoms/lectureCard/LectureCard.jsx
  src/components/UI/atoms/lectureCard/LectureCardStory.stories.js
  src/components/UI/atoms/lectureCard/ThreeLectureCard.jsx
  src/components/UI/atoms/lectureCard/ThreeLectureCardStory.stories.js
  src/components/UI/atoms/mobileLectureCard/MobileLectureCard.jsx
  src/components/UI/atoms/sorts/Sorts.jsx
  src/components/molecules/footer/Footer.jsx
  src/components/molecules/header/Header.jsx
  src/components/molecules/header/Header.stories.js
  src/components/molecules/hotsix/Hotsix.jsx
  src/components/molecules/selectCategory/SelectCategory.jsx
  src/components/molecules/suggestCherryPick/SuggestCherryPick.jsx
  src/components/pages/MobileNotificationPage.jsx
  src/components/pages/SearchResultPage.jsx
  src/components/templates/DetailTemplate.jsx
  src/components/templates/mainPageTemplate/MainPageTemplate.jsx
  src/components/templates/searchResultTemplate/SearchResultTemplate.jsx
  src/components/templates/searchResultTemplate/SearchResultTemplate.stories.js
Labels: feature, refactoring

#84 마이페이지 UI 구현완료
  src/components/UI/atoms/notification/Notification.jsx
  src/components/molecules/accountSetting/AccountSetting.jsx
  src/components/molecules/accountSetting/AccountSetting.stories.js
  src/components/molecules/bookmark/Bookmark.jsx
  src/components/molecules/bookmark/Bookmark.stories.js
  src/components/molecules/header/Header.jsx
  src/components/molecules/myReview/MyReview.jsx
  src/components/molecules/myReview/myReview.stories.js
  src/components/pages/MyPagePage.jsx
  src/components/templates/myPageTemplate/MyPageTemplate.jsx
  src/components/templates/myPageTemplate/MyPageTemplate.stories.js
Labels: feature, refactoring

#88 관리자 통계 분석 UI 구현
  src/components/molecules/header/ReviewAdminHeader.jsx
  src/components/templates/adminReviewDetail/AdminReviewDetail.stories.js
  src/components/templates/adminReviewDetailTemplate/AdminReviewDetailTemplate.jsx
  src/components/templates/adminReviewDetailTemplate/AdminReviewDetailTemplate.stories.js
  src/components/templates/adminStatisticsTemplate/AdminStatisticsTemplate.jsx
  src/components/templates/adminStatisticsTemplate/AdminStatisticsTemplate.stories.js
Labels: feature

#89 관리자 피드백 페이지 UI 구현
  src/components/templates/adminFeedbackTemplate/AdminFeedbackTemplate.jsx
  src/components/templates/adminFeedbackTemplate/AdminFeedbackTemplate.stories.js
Labels: feature

#92 관리자 리뷰 관리 페이지 수정
  src/components/templates/adminReviewTemplate/AdminReviewTemplate.jsx
Labels: refactoring

#93 관리자 페이지 뷰포트 80% 변경
  src/components/templates/adminFeedbackTemplate/AdminFeedbackTemplate.jsx
  src/components/templates/adminReviewDetailTemplate/AdminReviewDetailTemplate.jsx
  src/components/templates/adminStatisticsTemplate/AdminStatisticsTemplate.jsx
Labels: refactoring

#95 메인페이지 수정 및 추가
  src/assets/img/feedbackChecked.svg
  src/components/UI/atoms/feedback/Feedback.jsx
  src/components/molecules/header/Header.jsx
  src/components/molecules/hotsix/Hotsix.jsx
  src/components/molecules/mobileSort/MobileSort.jsx
  src/components/molecules/mobileSort/mobileSort.stories.js
  src/components/templates/mainPageTemplate/MainPageTemplate.jsx
Labels: bug, feature
